
rootProject.name = "leetcode"
include("RomanToInt")
include("LongestCommonPrefix")
include("AddTwoNumbers")
include("TwoSum")
include("PalindromeNumber")
include("ValidParentheses")
include("RemoveDuplicates")
include("StrStr")
include("SearchInsert")
include("LengthOfLastWord")
include("MyPow")
include("MySqrt")
include("CombinationSum")
include("IntegerToRoman")
include("ThreeSum")
include("ThreeSumClosest")
include("LetterCombinations")
include("FourSum")
include("GenerateParenthesis")
include("NextPermutation")
include("SearchInRotatedSortedArray")
